version: '3.3'

services:
  mysql-docker:
    image: mysql:8.0
    container_name: mysql-docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Secret12345
      MYSQL_DATABASE: auth
      MYSQL_USER: root
      MYSQL_PASSWORD: Secret12345@

  eureka-server:
    image: 20041998/eureka-server
    container_name: eureka-server
    restart: on-failure
    ports:
      - 8661:8661
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-server

  auth-server:
    image: 20041998/auth-server
    container_name: auth-server
    restart: on-failure
    ports:
      - 8888:8888
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-docker:3306/auth
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8661/eureka
    depends_on:
      - mysql-docker
      - eureka-server

  social-network-service:
    image: 20041998/social-network-service
    container_name: social-network-service
    ports:
      - 8080:8080
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8661/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-docker:3306/social_network_service?createDatabaseIfNotExist=true
    depends_on:
      - eureka-server
      - auth-server
      - media-service

  media-service:
    image: 20041998/media-service
    container_name: media-service
    ports:
      - 8081:8081
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8661/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-docker:3306/media?createDatabaseIfNotExist=true
    depends_on:
      - eureka-server

  gateway-service:
    image: 20041998/gateway-service
    container_name: gateway-service
    restart: on-failure
    ports:
      - 9090:9090
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8661/eureka
    depends_on:
      - auth-server
      - social-network-service

  angular-webapp:
    image: 20041998/angular-webapp
    container_name: angular-webapp
    restart: on-failure
    ports:
    - 80:80
    links:
      - gateway-service





