server:
  port: 9090

spring:
  application:
    name: gateway-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka
    instance:
      hostname: localhost

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  host:
    connect-timeout-milllis: 200000000
    socket-timeout-milllis: 200000000
  ignoredServices: '*'
  routes:
    social-network-service:
      path: /social/**
      serviceId: social-network-service
      stripPrefix: true
      sensitive-headers: Cookie,Set-Cookie
    auth-server:
      path: /auth/**
      serviceId: auth-server
      stripPrefix: true
      sensitive-headers: Cookie,Set-Cookie
  security:
    basic:
      enabled: false


