server:
  port: 9090

spring:
  application:
    name: gateway-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka
    instance:
      hostname: localhost

zuul:
  host:
    connect-timeout-milllis: 5000000
    socket-timeout-milllis: 5000000
  ignoredServices: '*'
  routes:
    social-network-service:
      path: /social/**
      serviceId: social-network-service
      stripPrefix: true
    auth-server:
      path: /auth/**
      serviceId: auth-server
      stripPrefix: true


